### ISSUE TITLE
[discuss] 关于该项目使用协议（LICENSE）的讨论

### ISSUE THREAD

**Issue by BobAnkh** [yuanyeon/notion#1]
我认为本项目主要作为一个文档项目，是否应该考虑使用更适合的协议，例如CC0-1.0, CC-BY-4.0或 CC-BY-SA-4.0，感觉MIT协议并不是很适合（个人观点）？

**Comment by HectorYuan** [comment]
你说得对，这个license我之前开源做得少，不太熟悉，看下来CC类是比较合适的，具体协议你有什么推荐么？

**Comment by BobAnkh** [comment]
这个该仓库将来的发展路径我暂时不是很清楚，所以建议您直接看看这个：[https://choosealicense.com/non-software/](https://choosealicense.com/non-software/)，这里有我提到的这三个主流的文档协议的介绍，您可以自己挑选一个，我觉得这3个都是比较主流常用的，所以都行，具体可能还要根据你一些其他需求来选择

**Comment by HectorYuan** [comment]
发展路径的话，目前是基于我的 notion 知识库，收录了网站、应用和软件、youtube 博主和博客&播客、一些设计法则&方法&框架，本身我这几个库结构都类似，可以同样使用csv2md产生页面；目前是这么设想的，我觉得可以先用 CC0-1.0

**Comment by BobAnkh** [comment]
👍

**Comment by BobAnkh** [comment]
Closes this since the LICENSE has been updated
